// "Did you know?" while an answer is being worked on (media/chat.js shows one under "Thinking…", a new one every ~15 s,
// with a Know more link). Kural tips link to the guide (the wiki); the rest are programming and computing facts linking
// to their source (MDN, the official docs, Wikipedia). Keep each one short (three lines in a narrow chat), true, and its link
// working: test/facts.test.js checks the shape; check new links by hand (curl -sIL <url>). No emoji.
// Loaded by the chat page as a plain script (window.KURAL_FACTS), and by the test with require().
(function () {
  const WIKI = "https://github.com/adithyakumarcr/kural/wiki/";
  // (Pages not on the published wiki yet: their file in the repository.)
  const DOCS = "https://github.com/adithyakumarcr/kural/blob/main/docs/wiki/";
  const MDN = "https://developer.mozilla.org/en-US/docs/";
  const GIT = "https://git-scm.com/docs/";
  const WP = "https://en.wikipedia.org/wiki/";
  const PY = "https://docs.python.org/3/";
  const BASH = "https://www.gnu.org/software/bash/manual/html_node/";
  const CODE = "https://code.visualstudio.com/docs/";
  const FACTS = [
    // ---------- Kural ----------
    { t: "Pressing Enter while Kural works doesn't stop it: your message is queued and read at its next step.", u: WIKI + "Chat" },
    { t: "Esc stops an answer. Anything you queued goes back into the box, so nothing is lost.", u: WIKI + "Chat" },
    { t: "Hover a message you sent and click Edit to change it and send it again from there.", u: WIKI + "Chat" },
    { t: "Restore code (hover a message you sent) puts back every file the AI changed after it.", u: WIKI + "Chat" },
    { t: "Fork from here starts a new chat from any message. This chat stays as it is.", u: WIKI + "Chat" },
    { t: "Type @ in the chat to mention a file from your project.", u: WIKI + "Chat" },
    { t: "You can paste a screenshot straight into the chat: the AI sees the picture.", u: WIKI + "Chat" },
    { t: "Plan mode writes a plan first and changes nothing. Build it then carries the plan out.", u: WIKI + "Chat" },
    { t: "Ask mode only answers: nothing in your project is changed.", u: WIKI + "Chat" },
    { t: "In Agent mode Kural asks before each command. Auto runs commands without asking.", u: WIKI + "Chat" },
    { t: "You can switch the mode while an answer runs: Agent to Auto runs the waiting commands at once.", u: WIKI + "Chat" },
    { t: "Drag a chat tab into the editor area to keep the chat beside your code.", u: WIKI + "Chat" },
    { t: "The small ring next to the send button shows how full this conversation's context is.", u: WIKI + "Chat" },
    { t: "The clock button has every chat from every workspace: search, pin or delete them.", u: WIKI + "Chat" },
    { t: "Moods change how the AI works with you: Explorer compares options, Critic looks for flaws.", u: WIKI + "Chat" },
    { t: "The Learn mood first checks what you already know, then teaches you step by step.", u: WIKI + "Chat" },
    { t: "You can make your own moods (Add your own mood… in the model menu): a name and a few sentences for the AI.", u: WIKI + "Chat" },
    { t: "Intensity, from Low to Max, sets how much the model thinks before it answers.", u: WIKI + "Chat" },
    { t: "Every file the AI changes shows under its answer: Review, Keep or Undo each one.", u: WIKI + "Chat" },
    { t: "Outside your project, Kural asks before the AI reads or changes a file (except in Auto mode).", u: WIKI + "Chat" },
    { t: "Click a picture in an answer to see it full size in its own tab.", u: WIKI + "Chat" },
    { t: "+ then Link ticket keeps a Jira ticket in mind for every message (Claude, with the Atlassian connector).", u: WIKI + "Chat" },
    { t: "The sparkle button in Source Control's message box writes a commit message from your changes.", u: WIKI + "Chat" },
    { t: "Ctrl+Alt+N (Cmd+Alt+N on a Mac) opens a new chat.", u: WIKI + "Chat" },
    { t: "Ctrl+K (Cmd+K on a Mac) changes the selected code in place, and you review it in red and green.", u: WIKI + "Inline-Edit" },
    { t: "In the terminal, type plain words like \"push this to main\" and press Tab: Kural suggests the command.", u: WIKI + "Terminal" },
    { t: "Tab Completion suggests code as you type; Tab accepts it. A small model on your computer makes it fast.", u: WIKI + "Tab-Completion" },
    { t: "Auto in the model menu lets the Model Router pick the model for each message.", u: DOCS + "Model-Router.md" },
    { t: "The Model Router's Cost profile saves your usage limits: the lightest model that can do the job.", u: DOCS + "Model-Router.md" },
    { t: "Multiple agents: a team with a project manager, researcher, architect, developers and a tester.", u: WIKI + "Multiple-Agents" },
    { t: "Your own model runs on your computer with Ollama: private, free, and it works offline.", u: WIKI + "Your-Own-Model" },
    { t: "Search & Ask: describe what you're looking for in plain words, and Kural lists the places.", u: DOCS + "Search-and-Ask.md" },
    { t: "In Kural's browser, pick an element on your page and Kural finds the code that makes it.", u: DOCS + "Browser.md" },
    { t: "Link a Raspberry Pi over SSH (+ then Link device) and the AI can run commands on it.", u: WIKI + "Devices" },
    { t: "Kural logs in to a device with its own SSH key: your password is used once and never saved.", u: WIKI + "Devices" },
    { t: "Hover the usage item in the status bar to see every limit: the Session (5 hours) and the Weekly one.", u: WIKI + "Account-and-Updates" },
    { t: "Kural Settings, Export settings: your preferences in a file, ready for another computer.", u: WIKI + "Account-and-Updates" },
    { t: "Get started can set up several AIs: Claude, Google Gemini, ChatGPT (Codex) and your own model.", u: WIKI + "Getting-Started" },
    { t: "Kural: Show Log lists every AI request Kural made, with timings.", u: WIKI + "Troubleshooting" },
    { t: "Google Gemini can't ask before a command: in Agent mode it edits files but runs no commands.", u: WIKI + "Google-Gemini-and-ChatGPT" },
    // ---------- programming and computing ----------
    { t: "Brendan Eich wrote the first version of JavaScript in ten days, in 1995, at Netscape.", u: WP + "Brendan_Eich" },
    { t: "Python is named after the comedy group Monty Python, not the snake.", u: PY + "faq/general.html#why-is-it-called-python" },
    { t: "Linus Torvalds created Git in 2005 to manage the Linux kernel's source code.", u: "https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git" },
    { t: "In 1947 a moth stuck in a relay of the Harvard Mark II was taped into its logbook: a real computer bug.", u: WP + "Software_bug" },
    { t: "Ada Lovelace published what is often called the first computer program in 1843.", u: WP + "Ada_Lovelace" },
    { t: "Grace Hopper wrote A-0 in 1951 and 1952, an early step toward compilers.", u: WP + "A-0_System" },
    { t: "UTF-8 was designed by Ken Thompson and Rob Pike in 1992, sketched on a placemat in a diner.", u: WP + "UTF-8" },
    { t: "0.1 + 0.2 gives 0.30000000000000004 in Python and JavaScript: decimals are stored in binary.", u: PY + "tutorial/floatingpoint.html" },
    { t: "typeof null is \"object\" in JavaScript: a leftover from the very first version of the language.", u: MDN + "Web/JavaScript/Reference/Operators/typeof" },
    { t: "[10, 9, 1].sort() gives [1, 10, 9] in JavaScript: without a compare function it sorts as text.", u: MDN + "Web/JavaScript/Reference/Global_Objects/Array/sort" },
    { t: "In JavaScript, == converts types before comparing (\"1\" == 1 is true); === doesn't.", u: MDN + "Web/JavaScript/Guide/Equality_comparisons_and_sameness" },
    { t: "NaN is the only JavaScript value that isn't equal to itself: test for it with Number.isNaN().", u: MDN + "Web/JavaScript/Reference/Global_Objects/NaN" },
    { t: "structuredClone() makes a deep copy of an object in JavaScript, including Maps, Sets and Dates.", u: MDN + "Web/API/Window/structuredClone" },
    { t: "console.table() shows an array of objects as a table in the browser's console.", u: MDN + "Web/API/console/table_static" },
    { t: "An async function in JavaScript always returns a Promise.", u: MDN + "Web/JavaScript/Reference/Statements/async_function" },
    { t: "JSON needs double quotes around keys and strings, and doesn't allow trailing commas.", u: MDN + "Web/JavaScript/Reference/Global_Objects/JSON" },
    { t: "The HTTP status 418 \"I'm a teapot\" began as an April Fools' joke, RFC 2324, in 1998.", u: MDN + "Web/HTTP/Reference/Status/418" },
    { t: "CORS errors come from the browser: the server has to say that other sites may call it.", u: MDN + "Web/HTTP/Guides/CORS" },
    { t: "DNS turns names like example.com into the numeric addresses computers connect to.", u: MDN + "Glossary/DNS" },
    { t: "The HTML <dialog> element gives you a built-in modal window.", u: MDN + "Web/HTML/Reference/Elements/dialog" },
    { t: "CSS :has() styles an element by what it contains, like a card that has an image.", u: MDN + "Web/CSS/Reference/Selectors/:has" },
    { t: "WebAssembly runs code compiled from C, C++ or Rust in the browser at near-native speed.", u: MDN + "WebAssembly" },
    { t: "TypeScript's types are checked, then erased: what runs is plain JavaScript.", u: "https://www.typescriptlang.org/docs/handbook/2/basic-types.html#erased-types" },
    { t: "Rust's ownership rules catch many memory bugs when you compile, without a garbage collector.", u: "https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html" },
    { t: "Python's style guide, PEP 8, asks for 4 spaces per indentation level.", u: "https://peps.python.org/pep-0008/#indentation" },
    { t: "Type import this in Python to read the Zen of Python: \"Beautiful is better than ugly.\"", u: "https://peps.python.org/pep-0020/" },
    { t: "Python's f'{x=}' prints the name and the value, like x=42 (Python 3.8 and newer).", u: PY + "whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging" },
    { t: "round(2.5) is 2 in Python: halfway values round to the even number.", u: PY + "builtins/functions.html#round" },
    { t: "Appending to a Python list is fast; inserting at the front is slow, because every item has to move.", u: "https://wiki.python.org/moin/TimeComplexity" },
    { t: "git bisect finds the commit that brought in a bug by halving the range of commits each step.", u: GIT + "git-bisect" },
    { t: "git reflog remembers where your branches pointed, so commits lost after a reset can usually be found.", u: GIT + "git-reflog" },
    { t: "git stash puts unfinished changes aside, so you can switch branches with a clean folder.", u: GIT + "git-stash" },
    { t: "git blame shows who last changed each line of a file, and in which commit.", u: GIT + "git-blame" },
    { t: "git add -p lets you stage a file piece by piece, choosing each change.", u: GIT + "git-add" },
    { t: "git switch -c name creates a branch and switches to it (Git 2.23 and newer).", u: GIT + "git-switch" },
    { t: "git log --oneline --graph draws your branches as a small text graph.", u: GIT + "git-log" },
    { t: "A .gitignore file tells Git which files never to track, like build output.", u: GIT + "gitignore" },
    { t: "Semantic Versioning is MAJOR.MINOR.PATCH: the MAJOR number goes up for breaking changes.", u: "https://semver.org/" },
    { t: "Rubber duck debugging: explaining your code line by line, even to a toy duck, often reveals the bug.", u: WP + "Rubber_duck_debugging" },
    { t: "Code checkers are called linters after Lint, a tool for C written at Bell Labs in 1978.", u: WP + "Lint_(software)" },
    { t: "Regular expressions come from mathematician Stephen Kleene's work on regular languages in 1951.", u: WP + "Regular_expression" },
    { t: "Markdown was created in 2004 by John Gruber, with Aaron Swartz.", u: WP + "Markdown" },
    { t: "The first known \"hello, world\" program is in Brian Kernighan's 1972 tutorial for the B language.", u: WP + "%22Hello,_World!%22_program" },
    { t: "Unicode has room for 1,114,112 code points; ASCII has 128 characters.", u: WP + "Unicode" },
    { t: "Unix time counts the seconds since 1 January 1970, UTC.", u: WP + "Unix_time" },
    { t: "Programs that keep Unix time in a signed 32-bit number run out on 19 January 2038.", u: WP + "Year_2038_problem" },
    { t: "In 1965 Gordon Moore predicted that chips would keep doubling their number of parts: Moore's law.", u: WP + "Moore%27s_law" },
    { t: "Binary search finds an item among a million sorted ones in about 20 steps.", u: WP + "Binary_search" },
    { t: "A hash table (a Python dict, a JavaScript Map) finds a key in about the same time however big it gets.", u: WP + "Hash_table" },
    { t: "Big O notation says how work grows with input: with O(n squared), twice the data means four times the work.", u: WP + "Big_O_notation" },
    { t: "A race condition is when the result depends on which of two things happens first.", u: WP + "Race_condition" },
    { t: "Test-driven development: write a failing test first, then just enough code to make it pass.", u: WP + "Test-driven_development" },
    { t: "localhost is your own computer: the address 127.0.0.1 (or ::1).", u: WP + "Localhost" },
    { t: "Linux began in 1991 as Linus Torvalds' hobby project.", u: WP + "History_of_Linux" },
    { t: "The first website, made by Tim Berners-Lee at CERN, can still be visited at info.cern.ch.", u: "https://info.cern.ch/" },
    { t: "Build database queries with parameters, never by pasting user input into the SQL: that's SQL injection.", u: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    { t: "The Twelve-Factor App keeps settings like API keys in environment variables, outside the code.", u: "https://12factor.net/config" },
    { t: "Ctrl+R in bash and zsh searches back through the commands you've run.", u: BASH + "Commands-For-History.html" },
    { t: "cd - takes you back to the folder you were in before.", u: BASH + "Bourne-Shell-Builtins.html" },
    { t: "In bash and zsh, !! repeats your last command: sudo !! runs it again with sudo.", u: BASH + "Event-Designators.html" },
    { t: "Ctrl+Shift+P (Cmd+Shift+P on a Mac) opens the Command Palette: every command, by name.", u: CODE + "editing/getting-started/userinterface#_command-palette" },
    { t: "Alt+Click (Option+Click on a Mac) adds another cursor, so you can type in several places at once.", u: CODE + "editing/codebasics#_multiple-selections-multi-cursor" },
    { t: "F2 renames a function or variable everywhere it's used, in languages that support it.", u: CODE + "editing/editingevolved#_rename-symbol" },
    { t: "F12 jumps to where a function or variable is defined.", u: CODE + "editing/editingevolved#_go-to-definition" },
    { t: "In the editor, Ctrl+P (Cmd+P on a Mac) opens any file of your project by typing part of its name.", u: CODE + "editing/editingevolved#_quick-file-navigation" },
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = FACTS;
  else window.KURAL_FACTS = FACTS;
})();
