#!/usr/bin/env node
// Trains Kural's word classifier (extension/lib/router/words.js) on extension/lib/router/examples.json and writes
// extension/lib/router/words-model.json. Run it after changing the examples: `node scripts/train-router.js`.
// Deterministic: the same examples give the same file (test/router-words.test.js checks the shipped file is current).
const fs = require("fs");
const path = require("path");
const { train, SIZES, KINDS } = require("../extension/lib/router/words");

function build() {
  const examples = require("../extension/lib/router/examples.json").examples;
  return { about: "Generated by scripts/train-router.js from examples.json: do not edit by hand.",
    examples: examples.length, size: train(examples, 1, SIZES), kind: train(examples, 2, KINDS) };
}

if (require.main === module) {
  const out = path.join(__dirname, "..", "extension", "lib", "router", "words-model.json");
  const t0 = Date.now(), m = build();
  fs.writeFileSync(out, JSON.stringify(m) + "\n");
  console.log(`wrote ${path.relative(process.cwd(), out)}: ${Object.keys(m.size.weights).length} + ${Object.keys(m.kind.weights).length} tokens, ` +
    `${(fs.statSync(out).size / 1024).toFixed(0)} KB, ${Date.now() - t0} ms`);
}
module.exports = { build };
